# Copyright Aeraki Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aeraki
  namespace: {{ .Release.Namespace }}
  labels:
    app: aeraki
spec:
  selector:
    matchLabels:
      app: aeraki
  replicas: {{ .Values.deployment.replicas }}
  template:
    metadata:
      labels:
        app: aeraki
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: aeraki
      containers:
        - name: aeraki
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          args:
            - /usr/local/bin/aeraki
            - --master=true
            - --enable-envoy-filter-namespace-scope=false
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 15010
            protocol: TCP
          - containerPort: 15017
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          env:
            - name: AERAKI_IS_MASTER
              value: {{ .Values.AERAKI_ENV.AERAKI_IS_MASTER }}
            - name: AERAKI_ISTIOD_ADDR
              value: {{ .Values.AERAKI_ENV.AERAKI_ISTIOD_ADDR }}
            - name: AERAKI_ISTIOD_CONFIGMAP_NAME
              value: {{ .Values.AERAKI_ENV.AERAKI_ISTIOD_CONFIGMAP_NAME }}
            - name: AERAKI_CLUSTER_ID
              value: {{ .Values.AERAKI_ENV.AERAKI_CLUSTER_ID }}
            # In case of TCM, Istio config store can be a different k8s API server from the one Aeraki is running with
            - name: AERAKI_ISTIO_CONFIG_STORE_SECRET
              value: {{ .Values.AERAKI_ENV.AERAKI_ISTIO_CONFIG_STORE_SECRET }}
            - name: AERAKI_XDS_ADDR
              value: {{ .Values.AERAKI_ENV.AERAKI_XDS_ADDR }}
            - name: AERAKI_XDS_PORT
              value: {{ .Values.AERAKI_ENV.AERAKI_XDS_PORT }}
            - name: AERAKI_LOG_LEVEL
              value: {{ .Values.AERAKI_ENV.AERAKI_LOG_LEVEL }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AERAKI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AERAKI_SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: istiod-ca-cert
              mountPath: /var/run/secrets/istio
              readOnly: true
      volumes:
        - name: istiod-ca-cert
          configMap:
            name: istio-ca-root-cert
            defaultMode: 420
